# Generated by Django 4.2.3 on 2023-07-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_actor_table_alter_movie_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(blank=True, choices=[('woman', 'Women'), ('mile', 'Mile')], max_length=10, null=True),
        ),
    ]
