# Generated by Django 4.2.3 on 2023-07-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_actor_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
