# Generated by Django 4.2.3 on 2023-07-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_actor_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='listened',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
