# Generated by Django 4.2.3 on 2023-07-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_movie_listened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='listened',
            new_name='view',
        ),
    ]
